using System;

public enum GameEvent
{
    HORIZONTAL_INPUT,
    VERTICAL_INPUT,
    MOUSE_X_INPUT,
    MOUSE_Y_INPUT,
    CHARACTER_MOVE,
    CHARACTER_ROTATE,
    CAMERA_ORBIT,
    CAMERA_SNAP,
    CAMERA_ZOOM,
    CHARACTER_JUMP,
    CHARACTER_FIRE1,
    CHARACTER_FIRE2,
    CHARACTER_FIRE3,
    CHARACTER_FIRESPECIAL,
    HIT_FROM_HUMAN,
    HIT_FROM_MONSTER,
    HIT_FROM_MECH

}
